import { RoleName, Resource, Action } from "@/types/rbac"

type PermissionMatrix = Partial<Record<Resource, Action[]>>

const SUPER_ADMIN_PERMISSIONS: PermissionMatrix = {
  dashboard: ["VIEW"],
  business_channels: ["VIEW", "CREATE", "UPDATE", "DELETE"],
  integrations: ["VIEW", "CREATE", "UPDATE", "DELETE", "EXECUTE"],
  catalog: ["VIEW", "CREATE", "UPDATE", "DELETE"],
  offers: ["VIEW", "CREATE", "UPDATE", "DELETE"],
  knowledge: ["VIEW", "CREATE", "UPDATE", "DELETE"],
  personas: ["VIEW", "CREATE", "UPDATE", "DELETE"],
  agents: ["VIEW", "CREATE", "UPDATE", "DELETE"],
  routing_rules: ["VIEW", "CREATE", "UPDATE", "DELETE"],
  prompt_templates: ["VIEW", "CREATE", "UPDATE", "DELETE"],
  automation_config: ["VIEW", "CREATE", "UPDATE", "DELETE"],
  contacts: ["VIEW", "UPDATE", "DELETE"],
  test_contacts: ["VIEW", "CREATE", "UPDATE", "DELETE"],
  whitelist: ["VIEW", "CREATE", "DELETE"],
  blacklist: ["VIEW", "CREATE", "DELETE"],
  contact_memory: ["VIEW", "UPDATE", "DELETE"],
  contact_policies: ["VIEW", "CREATE", "UPDATE", "DELETE"],
  policy_logs: ["VIEW"],
  sync_logs: ["VIEW"],
  maintenance_jobs: ["VIEW", "EXECUTE"],
  system_health: ["VIEW"],
  audit_logs: ["VIEW"],
  users: ["VIEW", "CREATE", "UPDATE", "DELETE"],
  roles: ["VIEW", "UPDATE"],
  security_settings: ["VIEW", "UPDATE"],
}

const ADMIN_PERMISSIONS: PermissionMatrix = {
  dashboard: ["VIEW"],
  business_channels: ["VIEW", "CREATE", "UPDATE", "DELETE"],
  integrations: ["VIEW", "CREATE", "UPDATE", "EXECUTE"],
  catalog: ["VIEW", "CREATE", "UPDATE", "DELETE"],
  offers: ["VIEW", "CREATE", "UPDATE", "DELETE"],
  knowledge: ["VIEW", "CREATE", "UPDATE", "DELETE"],
  personas: ["VIEW", "CREATE", "UPDATE"],
  agents: ["VIEW", "CREATE", "UPDATE"],
  routing_rules: ["VIEW", "CREATE", "UPDATE"],
  prompt_templates: ["VIEW", "CREATE", "UPDATE"],
  automation_config: ["VIEW", "UPDATE"],
  contacts: ["VIEW", "UPDATE", "DELETE"],
  test_contacts: ["VIEW", "CREATE", "UPDATE", "DELETE"],
  whitelist: ["VIEW", "CREATE", "DELETE"],
  blacklist: ["VIEW", "CREATE", "DELETE"],
  contact_memory: ["VIEW", "UPDATE"],
  contact_policies: ["VIEW", "CREATE", "UPDATE", "DELETE"],
  policy_logs: ["VIEW"],
  sync_logs: ["VIEW"],
  maintenance_jobs: ["VIEW", "EXECUTE"],
  system_health: ["VIEW"],
  audit_logs: ["VIEW"],
}

const READONLY_PERMISSIONS: PermissionMatrix = {
  dashboard: ["VIEW"],
  business_channels: ["VIEW"],
  integrations: ["VIEW"],
  catalog: ["VIEW"],
  offers: ["VIEW"],
  knowledge: ["VIEW"],
  personas: ["VIEW"],
  agents: ["VIEW"],
  routing_rules: ["VIEW"],
  prompt_templates: ["VIEW"],
  automation_config: ["VIEW"],
  contacts: ["VIEW"],
  test_contacts: ["VIEW"],
  whitelist: ["VIEW"],
  blacklist: ["VIEW"],
  contact_memory: ["VIEW"],
  contact_policies: ["VIEW"],
  policy_logs: ["VIEW"],
  sync_logs: ["VIEW"],
  maintenance_jobs: ["VIEW"],
  system_health: ["VIEW"],
  audit_logs: ["VIEW"],
}

export const ROLE_PERMISSIONS: Record<RoleName, PermissionMatrix> = {
  [RoleName.SUPER_ADMIN]: SUPER_ADMIN_PERMISSIONS,
  [RoleName.ADMIN]: ADMIN_PERMISSIONS,
  [RoleName.READONLY]: READONLY_PERMISSIONS,
}
